version: '3.8'
services:

  application:
#    build:
#      context: .
#      target: production
    image: application
    container_name: application
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MONGODB_URI=mongodb://root:secret@mongodb
    volumes:
      - data:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongo_db
    environment:
      - MONGO_INITDB_DATABASE=mygrocerylist
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_ROOT_USERNAME=root
    ports:
      - '27018:27017'
    volumes:
      - data:/var/lib/mongodb
volumes:
  data: